language: node_js
node_js:
  - '12'
cache: 
  yarn: true
  directories:
    - node_modules
    - ~/.npm
# git:
#   depth: 3
script:
  - yarn build
deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  target_branch: gh-pages
  commit_message: "Deploy de proyecto"
  on:
    branch: master