language: node_js
cache: 
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  cleanup: true
  keep_history: true
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy de proyecto"
  on:
    branch: master